version: "3.8"

services:

      
  accounts:
    image: fmc/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - fmcbank
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_PROFILES_ACTIVE: default
  
  loans:
    image: fmc/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - fmcbank
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_PROFILES_ACTIVE: default
    
  cards:
    image: fmc/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - fmcbank
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_PROFILES_ACTIVE: default
      
networks:
  fmcbank: